//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHangOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Category()
        {
            this.tb_News = new HashSet<tb_News>();
            this.tb_Posts = new HashSet<tb_Posts>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string SeoTitle { get; set; }
        public string SeoDiscription { get; set; }
        public string SeoKeywords { get; set; }
        public int Position { get; set; }
        public string CreactedBy { get; set; }
        public System.DateTime CreactedDate { get; set; }
        public System.DateTime ModifiedrDate { get; set; }
        public string ModifierBy { get; set; }
        public string Alias { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_News> tb_News { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Posts> tb_Posts { get; set; }
    }
}
