//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHangOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Posts
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int CategoryID { get; set; }
        public string Description { get; set; }
        public string Detail { get; set; }
        public string Image { get; set; }
        public string SeoTitle { get; set; }
        public string SeoDiscription { get; set; }
        public string SeoKeywords { get; set; }
        public string CreactedBy { get; set; }
        public System.DateTime CreactedDate { get; set; }
        public System.DateTime ModifiedrDate { get; set; }
        public string ModifierBy { get; set; }
        public string Alias { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> Category_Id { get; set; }
    
        public virtual tb_Category tb_Category { get; set; }
    }
}
